# Build stage
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Production stage
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app ./
RUN npm install -g pm2
EXPOSE 5000
CMD ["pm2-runtime", "index.js"]
